version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: prod
    image: django_todo_backend:${TAG:-latest}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backend_logs:/app/logs
    restart: always
    env_file:
      - ./backend/.env
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    image: react_todo_frontend:${TAG:-latest}
    ports:
      - "80:80"
    volumes:
      - ./frontend/frontend_logs:/app/logs
    restart: always