version: '3.9'

services:
  backend:
    ports:
      # Exposes application port.
      - "8001:8000"
    build:
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Adds current directory as volume.
      - ./backend:/app/src/
    restart: no
  frontend:
    ports:
      # Exposes application port.
      - "3000:3000"
    build: 
      target: build
    command: yarn start
    volumes:
      # Adds current directory as volume.
      - ./frontend:/app
    restart: no

